version: '3.9'
name: 'postgres_testes'

services:
  #Data Base
  postgres:
    image: postgres:latest
    restart: no
    environment:
      - POSTGRES_DB=teste
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    network_mode: host
#    volumes:
#      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
#    command: 'postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'